Repository Sahdeo-science-coaching/Coding_coaching, pull requests merged in 2020-10, with the labels that each got.

#1 Create index.html
  layout/index.html
Labels: documentation, hacktoberfest

#2 Create glasses_and_staches
  saved_media/glasses_and_staches
Labels: hactoberfest-accepted

#3 Create time-lapses.py
  src/src/time-lapses.py
Labels: hacktoberfest-accepted

#4 Create admission.html
  admission.html
Labels: hacktoberfest-accepted

#5 Create custom.js
  saved_media/js/custom.js
Labels: hacktoberfest-accepted

#6 Create easing.js
  saved_media/js/easing.js
Labels: hacktoberfest-accepted

#7 Create custom_review.html
  custom_review.html
Labels: hacktoberfest-accepted

#8 Create index.py
  admission/index.py
Labels: hacktoberfest-accepted
